server:
  port: ${PORT:2333}
  address: 0.0.0.0

lavalink:
  plugins:
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.8.3"
      repository: "https://maven.lavalink.dev/releases"
      snapshot: false
  server:
    password: "${LAVALINK_SERVER_PASSWORD}"
    sources:
      youtube: false
      bandcamp: false
      soundcloud: true
      twitch: false
      vimeo: false
      nico: false
      http: false
      local: false
    filters:
      volume: true
      equalizer: true

plugins:
  lavasrc:
    providers: []
    sources:
      spotify: false
      applemusic: false
      deezer: false
      yandexmusic: false
      flowerytts: false
      youtube: false
      vkmusic: false
      tidal: false
      qobuz: false
      ytdlp: true
      jiosaavn: false
    lyrics-sources:
      spotify: false
      deezer: false
      youtube: false
      yandexmusic: false
      vkmusic: false
      lrcLib: false
    ytdlp:
      path: "/usr/local/bin/yt-dlp"
      searchLimit: 1
      mixPlaylistLoadLimit: 1
      playlistLoadLimit: 1

logging:
  file:
    path: ./logs/
  level:
    root: INFO
    lavalink: INFO
